services:
  postgres:
    image: postgres:15-alpine
    container_name: akowe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-akowe_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-akowe_password}
      POSTGRES_DB: ${DB_NAME:-akowe}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: akowe-web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
      - migrations_data:/app/migrations
    ports:
      - "5000:5000"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: akowe-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin_data:
  migrations_data: