apiVersion: v1
kind: ConfigMap
metadata:
  name: akowe-config
  namespace: wackops
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  # These values should be changed to match your Azure Database for PostgreSQL
  DB_HOST: "your-azure-postgres-server.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "akowe"
---
apiVersion: v1
kind: Secret
metadata:
  name: akowe-secrets
  namespace: wackops
type: Opaque
stringData:
  SECRET_KEY: "kfXpE0ZW7hfXP9KUlBnS8jK3yM6RgT2L"  # Change this in production!
  # Update these with your Azure Database credentials
  DB_USER: "akowe_user@your-azure-postgres-server"
  DB_PASSWORD: "akowe_password"  # Change this in production!
  # Admin user settings
  ADMIN_USERNAME: "admin"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "Admin123!"  # Change this in production!
  ADMIN_FIRST_NAME: "Admin"
  ADMIN_LAST_NAME: "User"