apiVersion: apps/v1
kind: Deployment
metadata:
  name: akowe
  namespace: wackops
  labels:
    app: akowe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akowe
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akowe
    spec:
      containers:
      - name: akowe
        image: wackopsprodacr.azurecr.io/akowe:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: akowe-config
        - secretRef:
            name: akowe-secrets
        env:
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: instance-volume
          mountPath: /app/instance
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: akowe-data-pvc
      - name: instance-volume
        persistentVolumeClaim:
          claimName: akowe-instance-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akowe-data-pvc
  namespace: wackops
spec:
  storageClassName: azurefile-csi 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akowe-instance-pvc
  namespace: wackops
spec:
  storageClassName: azurefile-csi 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi